spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  jpa:
    database: default
    hibernate:      ddl-auto: update
      use-new-id-generator-mappings: false
  datasource:    url: jdbc:mysql://localhost:3306/user_db?allowPublicKeyRetrieval=true&useSSL=false&&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver